### PR TITLE
Update UpBeat.js

### PR DESCRIPTION
**Pull request by callumok2004**

### CODE REVIEW

**Comment by PiggyPlex** [comment]
we aren't having song art

**Comment by ImJustBluey** [comment]
noobs

**Comment by G3VV** [comment]
https://user-images.githubusercontent.com/46306494/141651806-cc7bad24-c439-43c1-a4f9-f0b5d9a0595e.mov

**Comment by PiggyPlex** [comment]
TW: the above comment marked as off-topic contains jump-scares and flashing imagery.

**Pull request closed without merging**
